flowchart LR
    subgraph examples__anonymize_code
        examples__anonymize_code__anonymize_and_compare["anonymize_and_compare"]
        examples__anonymize_code__main["main"]
    end
    subgraph examples__batch_scan
        examples__batch_scan__scan_project["scan_project"]
        examples__batch_scan__main["main"]
    end
    subgraph src__prollama
        src__prollama__auth__save_github_token["save_github_token"]
        src__prollama__router__model_router__ModelRouter__select["select"]
        src__prollama__auth__get_git_user_info["get_git_user_info"]
        src__prollama__auth__is_logged_in["is_logged_in"]
        src__prollama__auth__get_github_username["get_github_username"]
        src__prollama__cli___load_config["_load_config"]
        src__prollama__pr__get_current_repo["get_current_repo"]
        src__prollama__shell__ProllamaShell___cmd_solve["_cmd_solve"]
        src__prollama__integrations__planfile__PlanfileAdapter___load_token["_load_token"]
        src__prollama__cli__anonymize["anonymize"]
        src__prollama__pr__create_branch["create_branch"]
        src__prollama__cli__solve["solve"]
        src__prollama__cli__shell["shell"]
        src__prollama__config__Config__load["load"]
        src__prollama__auth__load_github_token["load_github_token"]
        src__prollama__cli___print_banner["_print_banner"]
        src__prollama__integrations__planfile__PlanfileAdapter___detect_repo["_detect_repo"]
        src__prollama__cli__config_show["config_show"]
        src__prollama__cli__ticket["ticket"]
        src__prollama__cli__status["status"]
        src__prollama__pr__create_pr_from_solve["create_pr_from_solve"]
        src__prollama__executor__task_executor__classify_type["classify_type"]
        src__prollama__cli__login["login"]
        src__prollama__cli__init["init"]
        src__prollama__router__model_router___complexity_to_start_tier["_complexity_to_start_tier"]
        src__prollama__integrations__planfile__create_prollama_ticket["create_prollama_ticket"]
        src__prollama__cli__sync["sync"]
        src__prollama__proxy__create_app["create_app"]
        src__prollama__auth__login_device_flow["login_device_flow"]
        src__prollama__config__Config__write_template["write_template"]
        src__prollama__cli__check["check"]
        src__prollama__executor__task_executor__TaskExecutor__solve["solve"]
        src__prollama__auth__get_auth_headers["get_auth_headers"]
        src__prollama__proxy__Proxy__get_app["get_app"]
        src__prollama__integrations__planfile__is_planfile_available["is_planfile_available"]
        src__prollama__auth__logout["logout"]
        src__prollama__cli__start["start"]
        src__prollama__executor__task_executor__classify_complexity["classify_complexity"]
        src__prollama__pr__create_pull_request["create_pull_request"]
        src__prollama__auth__get_credentials_path["get_credentials_path"]
        src__prollama__auth___login_manual_token["_login_manual_token"]
        src__prollama__auth__get_local_username["get_local_username"]
    end
    examples__batch_scan__main --> examples__batch_scan__scan_project
    examples__anonymize_code__main --> examples__anonymize_code__anonymize_and_compare
    src__prollama__proxy__Proxy__get_app --> src__prollama__proxy__create_app
    src__prollama__auth__save_github_token --> src__prollama__auth__get_credentials_path
    src__prollama__auth__load_github_token --> src__prollama__auth__get_credentials_path
    src__prollama__auth__get_local_username --> src__prollama__auth__get_credentials_path
    src__prollama__auth__get_local_username --> src__prollama__auth__get_git_user_info
    src__prollama__auth__login_device_flow --> src__prollama__auth__is_logged_in
    src__prollama__auth__login_device_flow --> src__prollama__auth__load_github_token
    src__prollama__auth___login_manual_token --> src__prollama__auth__get_github_username
    src__prollama__auth___login_manual_token --> src__prollama__auth__save_github_token
    src__prollama__auth__logout --> src__prollama__auth__get_credentials_path
    src__prollama__auth__is_logged_in --> src__prollama__auth__load_github_token
    src__prollama__auth__get_auth_headers --> src__prollama__auth__load_github_token
    src__prollama__cli___load_config --> src__prollama__config__Config__load
    src__prollama__cli__login --> src__prollama__auth__login_device_flow
    src__prollama__cli__ticket --> src__prollama__integrations__planfile__create_prollama_ticket
    src__prollama__cli__ticket --> src__prollama__integrations__planfile__is_planfile_available
    src__prollama__cli__init --> src__prollama__config__Config__write_template
    src__prollama__cli__start --> src__prollama__cli___load_config
    src__prollama__cli__start --> src__prollama__proxy__create_app
    src__prollama__cli__status --> src__prollama__cli___load_config
    src__prollama__cli__status --> src__prollama__cli___print_banner
    src__prollama__cli__solve --> src__prollama__cli___load_config
    src__prollama__cli__anonymize --> src__prollama__cli___load_config
    src__prollama__cli__config_show --> src__prollama__cli___load_config
    src__prollama__cli__check --> src__prollama__auth__is_logged_in
    src__prollama__cli__check --> src__prollama__integrations__planfile__is_planfile_available
    src__prollama__cli__check --> src__prollama__cli___load_config
    src__prollama__cli__check --> src__prollama__pr__get_current_repo
    src__prollama__cli__sync --> src__prollama__cli___load_config
    src__prollama__cli__shell --> src__prollama__cli___load_config
    src__prollama__shell__ProllamaShell___cmd_solve --> src__prollama__executor__task_executor__classify_complexity
    src__prollama__shell__ProllamaShell___cmd_solve --> src__prollama__executor__task_executor__classify_type
    src__prollama__pr__create_pull_request --> src__prollama__auth__load_github_token
    src__prollama__pr__create_pull_request --> src__prollama__pr__get_current_repo
    src__prollama__pr__create_pr_from_solve --> src__prollama__pr__get_current_repo
    src__prollama__pr__create_pr_from_solve --> src__prollama__pr__create_pull_request
    src__prollama__pr__create_pr_from_solve --> src__prollama__pr__create_branch
    src__prollama__executor__task_executor__TaskExecutor__solve --> src__prollama__executor__task_executor__classify_type
    src__prollama__executor__task_executor__TaskExecutor__solve --> src__prollama__executor__task_executor__classify_complexity
    src__prollama__integrations__planfile__PlanfileAdapter___detect_repo --> src__prollama__pr__get_current_repo
    src__prollama__integrations__planfile__PlanfileAdapter___load_token --> src__prollama__auth__load_github_token
    src__prollama__router__model_router__ModelRouter__select --> src__prollama__router__model_router___complexity_to_start_tier
