flowchart TD
    examples__anonymize_code["examples.anonymize_code<br/>2 funcs"]
    examples__batch_scan["examples.batch_scan<br/>2 funcs"]
    examples__routing_demo["examples.routing_demo<br/>1 funcs"]
    examples__sample_code["examples.sample_code<br/>39 funcs"]
    src__prollama["src.prollama<br/>98 funcs"]
