flowchart TD
    examples__anonymize_code["examples.anonymize_code<br/>2 funcs"]
    examples__batch_scan["examples.batch_scan<br/>2 funcs"]
    examples__routing_demo["examples.routing_demo<br/>1 funcs"]
    examples__sample_code["examples.sample_code<br/>28 funcs"]
    examples__workflow["examples.workflow<br/>3 funcs"]
    src__prollama["src.prollama<br/>167 funcs"]
